all:
	@(cd redis_key; make)
	@(cd redis_string; make)
	@(cd redis_hash; make)
	@(cd redis_pool; make)
	@(cd redis_manager; make)
	@(cd redis_pubsub; make)
	@(cd redis_zset; make)

clean:
	@(cd redis_key; make clean)
	@(cd redis_string; make clean)
	@(cd redis_hash; make clean)
	@(cd redis_pool; make clean)
	@(cd redis_manager; make clean)
	@(cd redis_pubsub; make clean)
	@(cd redis_zset; make clean)
