.PHONY = all clean
all:
	@(cd liburl; make)
	@(cd url_coder; make)
	@(cd libws; make)
	@(cd websocket; make)
clean:
	@(cd liburl; make clean)
	@(cd url_coder; make clean)
	@(cd libws; make clean)
	@(cd websocket; make clean)
