
all:
	@(cd benchmark; make)
	@(cd test; make)
	@(cd test0; make)
	@(cd test1; make)
	@(cd test2; make)
	@(cd test3; make)
clean:
	@(cd benchmark; make clean)
	@(cd test; make clean)
	@(cd test0; make clean)
	@(cd test1; make clean)
	@(cd test2; make clean)
	@(cd test3; make clean)
