.PHONY = all clean

all:
	@(cd mime; make)
	@(cd mime_qp; make)
	@(cd mime_base64; make)
	@(cd mime_xxcode; make)

clean:
	@(cd mime; make clean)
	@(cd mime_qp; make clean)
	@(cd mime_base64; make clean)
	@(cd mime_xxcode; make clean)
