all:
#	@(cd thread1; make)
#	@(cd thread_pool1; make)
	@(cd thread_pool2; make)
	@(cd thread_pool3; make)
clean:
	@(cd thread1; make clean)
	@(cd thread_pool1; make clean)
	@(cd thread_pool2; make clean)
	@(cd thread_pool3; make clean)
