.PHONY = all clean

all:
	@(cd json0; make)
	@(cd json1; make)
	@(cd json2; make)
	@(cd json3; make)
	@(cd json4; make)
	@(cd json5; make)
	@(cd json6; make)
	@(cd json7; make)
clean:
	@(cd json0; make clean)
	@(cd json1; make clean)
	@(cd json2; make clean)
	@(cd json3; make clean)
	@(cd json4; make clean)
	@(cd json5; make clean)
	@(cd json6; make clean)
	@(cd json7; make clean)
