.PHONY = all clean

all:
	@(cd url_get1; make)
	@(cd url_get2; make)
	@(cd url_get3; make)
	@(cd header; make)
clean:
	@(cd url_get1; make clean)
	@(cd url_get2; make clean)
	@(cd url_get3; make clean)
	@(cd header; make clean)
