.PHONY = all clean

all:
	@(cd http_request; make)
	@(cd http_response; make)
	@(cd http_servlet; make)

clean:
	@(cd http_request; make clean)
	@(cd http_response; make clean)
	@(cd http_servlet; make clean)
